FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt to the container
COPY requirements.txt /app/requirements.txt

# Menyalin requirements.txt ke container
COPY requirements.txt /app/

# Menginstal dependensi yang ada di requirements.txt
RUN pip install -r /app/requirements.txt

# Copy all project files into the container
COPY . /app

# Expose the port that the app will run on
EXPOSE 3001

CMD ["gunicorn", "app:app", "-b", "0.0.0.0:3001"]
