# Menggunakan image Node.js sebagai base
FROM node:16

# Set working directory
WORKDIR /app

# Salin file package.json dan package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Salin seluruh file aplikasi frontend
COPY . .

# Expose port tempat aplikasi frontend berjalan
EXPOSE 3000

# Jalankan aplikasi dalam mode pengembangan (dev)
CMD ["npm", "run", "dev"]
